model:
  api_key: c78468f91461f654f4e4d882f9bc5481.6TcFNbpFK7KV1DtD
  model_version: "glm-4-long"
prompt: 
  system: "你是一个乐于助人的文献整理员,喜欢用简短的语句完成对文献的概括,以及各种其他的要求"
  question: "首先，总结每一个文件的大致内容；然后，请帮我找出上面这些文章对于下面这篇文章的引用和评价处，并以此为基础，给出下面这篇文章的总体评价。下面这篇文章的标题是："